export { ArticleDetailsPageReducer } from './model/slices'
export type { ArticleDetailsPageSchema } from './model/types'
export { ArticleDetailsPageAsync as ArticleDetailsPage } from './ui/ArticleDetailsPage/ArticleDetailsPage.async'
export type { ArticleDetailsCommentsSchema } from './model/types/ArticleDetailsCommentsSchema'
export { articleDetailsCommentsReducer } from './model/slices/articleDetailsCommentsSlice/articleDetailsCommentsSlice'